[SENSORMODE]
ATTR = [ "WRITABLE", "READABLE",]
TYPE = "MODE"
default = 1.0
id = 4194832
max = 16.0
min = 1.0
name = "SENSOR MODE"

	[SENSORMODE.support]
	1 = "AREA"
	2 = "PROGRESSIVE"
	3 = "SPLIT VIEW"
	4 = "DUAL LIGHT SHEET"

[READOUTSPEED]
ATTR = [ "WRITABLE", "READABLE",]
TYPE = "LONG"
default = 2.0
id = 4194576
max = 2.0
min = 1.0
name = "READOUT SPEED"
step = 1.0

[READOUT_DIRECTION]
ATTR = [ "READABLE",]
TYPE = "MODE"
default = 5.0
id = 4194608
max = 5.0
min = 5.0
name = "READOUT DIRECTION"

	[READOUT_DIRECTION.support]
	1 = "DIVERGE"

[COLORTYPE]
ATTR = [ "READABLE", "DATASTREAM",]
TYPE = "MODE"
default = 1.0
id = 4325664
max = 1.0
min = 1.0
name = "COLORTYPE"

	[COLORTYPE.support]
	1 = "B/W"

[BITSPERCHANNEL]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "LONG"
default = 16.0
id = 4325680
max = 16.0
min = 12.0
name = "BIT PER CHANNEL"
step = 4.0

[TRIGGERSOURCE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 1.0
id = 1048848
max = 4.0
min = 1.0
name = "TRIGGER SOURCE"

	[TRIGGERSOURCE.support]
	1 = "INTERNAL"
	2 = "EXTERNAL"
	3 = "SOFTWARE"
	4 = "MASTER PULSE"

[TRIGGER_MODE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY",]
TYPE = "MODE"
default = 1.0
id = 1049104
max = 6.0
min = 1.0
name = "TRIGGER MODE"

	[TRIGGER_MODE.support]
	1 = "NORMAL"
	2 = "START"

[TRIGGERACTIVE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY",]
TYPE = "MODE"
default = 1.0
id = 1048864
max = 3.0
min = 1.0
name = "TRIGGER ACTIVE"

	[TRIGGERACTIVE.support]
	1 = "EDGE"
	2 = "LEVEL"
	3 = "SYNCREADOUT"

[TRIGGER_GLOBALEXPOSURE]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "MODE"
default = 3.0
id = 2032384
max = 5.0
min = 3.0
name = "TRIGGER GLOBAL EXPOSURE"

	[TRIGGER_GLOBALEXPOSURE.support]
	1 = "DELAYED"
	2 = "GLOBAL RESET"

[TRIGGERPOLARITY]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 1.0
id = 1049120
max = 2.0
min = 1.0
name = "TRIGGER POLARITY"

	[TRIGGERPOLARITY.support]
	1 = "NEGATIVE"
	2 = "POSITIVE"

[TRIGGER_CONNECTOR]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 2.0
id = 1049136
max = 2.0
min = 2.0
name = "TRIGGER CONNECTOR"

	[TRIGGER_CONNECTOR.support]
	1 = "BNC"

[TRIGGERTIMES]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
default = 1.0
id = 1049152
max = 10000.0
min = 1.0
name = "TRIGGER TIMES"
step = 1.0

[TRIGGERDELAY]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "AUTOROUNDING",]
TYPE = "REAL"
default = 0.0
id = 1049184
max = 10.000003999999999
min = 0.0
name = "TRIGGER DELAY"
step = 1e-6

[INTERNALTRIGGER_HANDLING]
ATTR = [ "READABLE", "ACCESSREADY",]
TYPE = "MODE"
default = 1.0
id = 1049200
max = 1.0
min = 1.0
name = "INTERNAL TRIGGER HANDLING"

	[INTERNALTRIGGER_HANDLING.support]
	1 = "SHORTER EXPOSURE TIME"

[SENSORTEMPERATURE]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY", "VOLATILE",]
TYPE = "REAL"
id = 2097936
max = 100.0
min = -50.0
name = "SENSOR TEMPERATURE"
step = 1.0

[SENSORCOOLERSTATUS]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY", "VOLATILE",]
TYPE = "MODE"
id = 2097984
max = 3.0
min = 1.0
name = "SENSOR COOLER STATUS"

	[SENSORCOOLERSTATUS.support]
	1 = "OFF"
	2 = "READY"
	3 = "BUSY"

[EXPOSURETIME]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "AUTOROUNDING",]
TYPE = "REAL"
default = 0.009997714285714287
id = 2031888
max = 10.000004210526317
min = 0.0010036691729323308
name = "EXPOSURE TIME"
step = 1e-8

[DEFECTCORRECT_MODE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 2.0
id = 4653072
max = 2.0
min = 1.0
name = "DEFECT CORRECT MODE"

	[DEFECTCORRECT_MODE.support]
	1 = "OFF"
	2 = "ON"

[HOTPIXELCORRECT_LEVEL]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 1.0
id = 4653104
max = 3.0
min = 1.0
name = "HOT PIXEL CORRECT LEVEL"

	[HOTPIXELCORRECT_LEVEL.support]
	1 = "STANDARD"
	2 = "MINIMUM"
	3 = "AGGRESSIVE"

[BINNING]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "MODE"
default = 1.0
id = 4198672
max = 4.0
min = 1.0
name = "BINNING"

	[BINNING.support]
	1 = "1x1"
	2 = "2x2"
	3 = "4x4"

[SUBARRAYHPOS]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "LONG"
default = 0.0
id = 4202768
max = 2044.0
min = 0.0
name = "SUBARRAY HPOS"
step = 4.0

[SUBARRAYHSIZE]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "LONG"
default = 2048.0
id = 4202784
max = 2048.0
min = 4.0
name = "SUBARRAY HSIZE"
step = 4.0

[SUBARRAYVPOS]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "LONG"
default = 0.0
id = 4202800
max = 2044.0
min = 0.0
name = "SUBARRAY VPOS"
step = 4.0

[SUBARRAYVSIZE]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "LONG"
default = 2048.0
id = 4202816
max = 2048.0
min = 4.0
name = "SUBARRAY VSIZE"
step = 4.0

[SUBARRAYMODE]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "MODE"
default = 1.0
id = 4202832
max = 2.0
min = 1.0
name = "SUBARRAY MODE"

	[SUBARRAYMODE.support]
	1 = "OFF"
	2 = "ON"

[INTENSITYLUT_MODE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY",]
TYPE = "MODE"
default = 1.0
id = 3671312
max = 2.0
min = 1.0
name = "INTENSITY LUT MODE"

	[INTENSITYLUT_MODE.support]
	1 = "THROUGH"
	2 = "PAGE"

[INTENSITYLUT_PAGE]
ATTR = [ "READABLE", "ACCESSREADY",]
TYPE = "MODE"
default = 1.0
id = 3671328
max = 1.0
min = 1.0
name = "INTENSITY LUT PAGE"

	[INTENSITYLUT_PAGE.support]
	1 = "1"

[EXTRACTION_MODE]
ATTR = [ "READABLE", "DATASTREAM",]
TYPE = "MODE"
id = 4195872
name = "EXTRACTION MODE"

	[EXTRACTION_MODE.support]
	1 = "OFF"

[TIMING_READOUTTIME]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4206608
name = "TIMING READOUT TIME"

[TIMING_CYCLICTRIGGERPERIOD]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4206624
name = "TIMING CYCLIC TRIGGER PERIOD"

[TIMING_MINTRIGGERBLANKING]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4206640
name = "TIMING MIN TRIGGER BLANKING"

[TIMING_MINTRIGGERINTERVAL]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4206672
name = "TIMING MIN TRIGGER INTERVAL"

[TIMING_GLOBALEXPOSUREDELAY]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4206736
max = 0.024994285714285715
min = 0.0
name = "TIMING GLOBAL EXPOSURE DELAY"

[TIMING_EXPOSURE]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 1.0
id = 4206688
max = 3.0
min = 1.0
name = "TIMING EXPOSURE"

	[TIMING_EXPOSURE.support]
	1 = "AFTER READOUT"
	2 = "ROLLING"

[TIMING_INVALIDEXPOSUREPERIOD]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4206704
max = 0.014996571428571429
min = 0.0
name = "TIMING INVALID EXPOSURE PERIOD"

[INTERNALFRAMERATE]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4208656
max = 40.00914494741655
min = 0.09999995789475456
name = "INTERNAL FRAME RATE"
step = 0.0

[INTERNAL_FRAMEINTERVAL]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4208672
max = 10.000004210526317
min = 0.024994285714285715
name = "INTERNAL FRAME INTERVAL"
step = 0.0

[INTERNALLINESPEED]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4208704
max = 0.6670524691358024
min = 0.6670524691358024
name = "INTERNAL LINE SPEED"
step = 0.0

[INTERNAL_LINEINTERVAL]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4208720
max = 9.74436090225564e-6
min = 9.74436090225564e-6
name = "INTERNAL LINE INTERVAL"
step = 0.0

[FRAMEBUNDLE_MODE]
ATTR = [ "READABLE", "DATASTREAM",]
TYPE = "MODE"
default = 1.0
id = 4329488
max = 1.0
min = 1.0
name = "FRAMEBUNDLE MODE"

	[FRAMEBUNDLE_MODE.support]
	1 = "OFF"

[FRAMEBUNDLE_NUMBER]
ATTR = [ "READABLE", "DATASTREAM",]
TYPE = "LONG"
default = 2.0
id = 4329504
max = 2.0
min = 2.0
name = "FRAMEBUNDLE NUMBER"
step = 0.0

[FRAMEBUNDLE_ROWBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4329520
max = 4096.0
min = 4096.0
name = "FRAMEBUNDLE ROWBYTES"
step = 4096.0

[FRAMEBUNDLE_FRAMESTEPBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4329536
max = 8388608.0
min = 8388608.0
name = "FRAMEBUNDLE FRAME STEP BYTES"
step = 8388608.0

[IMAGE_WIDTH]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4325904
max = 2048.0
min = 4.0
name = "IMAGE WIDTH"
step = 1.0

[IMAGE_HEIGHT]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4325920
max = 2048.0
min = 4.0
name = "IMAGE HEIGHT"
step = 1.0

[IMAGE_ROWBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4325936
max = 4096.0
min = 2.0
name = "IMAGE ROWBYTES"
step = 2.0

[IMAGE_FRAMEBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4325952
max = 8388608.0
min = 2.0
name = "IMAGE FRAMEBYTES"
step = 2.0

[IMAGE_TOPOFFSETBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4325968
max = 0.0
min = 0.0
name = "IMAGE TOP OFFSET BYTES"
step = 0.0

[IMAGE_PIXELTYPE]
ATTR = [ "WRITABLE", "READABLE",]
TYPE = "MODE"
default = 2.0
id = 4326000
max = 3.0
min = 1.0
name = "IMAGE PIXEL TYPE"

	[IMAGE_PIXELTYPE.support]
	1 = "MONO8"
	2 = "MONO16"
	3 = "MONO12"

[IMAGE_CAMERASTAMP]
ATTR = [ "WRITABLE", "READABLE", "DATASTREAM",]
TYPE = "LONG"
default = 0.0
id = 4326144
max = 65535.0
min = 0.0
name = "IMAGE CAMERA STAMP"
step = 1.0

[BUFFER_ROWBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4326192
max = 4096.0
min = 2.0
name = "BUFFER ROWBYTES"
step = 1.0

[BUFFER_FRAMEBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4326208
max = 8388608.0
min = 2.0
name = "BUFFER FRAMEBYTES"
step = 1.0

[BUFFER_TOPOFFSETBYTES]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4326224
max = 0.0
min = 0.0
name = "BUFFER TOP OFFSET BYTES"
step = 0.0

[BUFFER_PIXELTYPE]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 2.0
id = 4326240
max = 3.0
min = 1.0
name = "BUFFER PIXEL TYPE"

	[BUFFER_PIXELTYPE.support]
	1 = "MONO8"
	2 = "MONO16"
	3 = "MONO12"

[RECORDFIXEDBYTES_PERFILE]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4326416
max = 256.0
min = 256.0
name = "RECORD FIXED BYTES PER FILE"
step = 1.0

[RECORDFIXEDBYTES_PERSESSION]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4326432
max = 1088.0
min = 0.0
name = "RECORD FIXED BYTES PER SESSION"
step = 1.0

[RECORDFIXEDBYTES_PERFRAME]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4326448
max = 8388688.0
min = 0.0
name = "RECORD FIXED BYTES PER FRAME"
step = 1.0

[NUMBEROF_OUTPUTTRIGGERCONNECTOR]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 1835024
name = "NUMBER OF OUTPUT TRIGGER CONNECTOR"

[OUTPUTTRIGGER_SOURCE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "ARRAYBASE",]
TYPE = "MODE"
default = 2.0
id = 1835280
max = 6.0
min = 2.0
name = "OUTPUT TRIGGER SOURCE[0]"

	[OUTPUTTRIGGER_SOURCE.support]
	1 = "READOUT END"
	2 = "VSYNC"
	3 = "TRIGGER"

[OUTPUTTRIGGER_POLARITY]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "ARRAYBASE",]
TYPE = "MODE"
default = 1.0
id = 1835296
max = 2.0
min = 1.0
name = "OUTPUT TRIGGER POLARITY[0]"

	[OUTPUTTRIGGER_POLARITY.support]
	1 = "NEGATIVE"
	2 = "POSITIVE"

[OUTPUTTRIGGER_ACTIVE]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY", "ARRAYBASE",]
TYPE = "MODE"
default = 1.0
id = 1835312
max = 1.0
min = 1.0
name = "OUTPUT TRIGGER ACTIVE[0]"

	[OUTPUTTRIGGER_ACTIVE.support]
	1 = "EDGE"

[OUTPUTTRIGGER_DELAY]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "AUTOROUNDING", "ARRAYBASE",]
TYPE = "REAL"
default = 0.0
id = 1835328
max = 10.0
min = 0.0
name = "OUTPUT TRIGGER DELAY[0]"
step = 1e-6

[OUTPUTTRIGGER_PERIOD]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "AUTOROUNDING", "ARRAYBASE",]
TYPE = "REAL"
default = 1e-6
id = 1835344
max = 10.0
min = 1e-6
name = "OUTPUT TRIGGER PERIOD[0]"
step = 1e-6

[OUTPUTTRIGGER_KIND]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "ARRAYBASE",]
TYPE = "MODE"
default = 1.0
id = 1835360
max = 5.0
min = 1.0
name = "OUTPUT TRIGGER KIND[0]"

	[OUTPUTTRIGGER_KIND.support]
	1 = "LOW"
	2 = "EXPOSURE"
	3 = "PROGRAMABLE"
	4 = "TRIGGER READY"
	5 = "HIGH"

[OUTPUTTRIGGER_BASESENSOR]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "ARRAYBASE",]
TYPE = "MODE"
default = 16.0
id = 1835376
max = 16.0
min = 1.0
name = "OUTPUT TRIGGER BASE SENSOR[0]"

	[OUTPUTTRIGGER_BASESENSOR.support]
	1 = "VIEW 1"
	2 = "VIEW 2"
	3 = "ANY VIEW"
	4 = "ALL VIEWS"

[OUTPUTTRIGGER_PREHSYNCCOUNT]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
default = 0.0
id = 1835408
max = 2047.0
min = 0.0
name = "OUTPUT TRIGGER PRE HSYNC COUNT"
step = 1.0

[MASTERPULSE_MODE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 1.0
id = 1966112
max = 3.0
min = 1.0
name = "MASTER PULSE MODE"

	[MASTERPULSE_MODE.support]
	1 = "CONTINUOUS"
	2 = "START"
	3 = "BURST"

[MASTERPULSE_TRIGGERSOURCE]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 1.0
id = 1966128
max = 2.0
min = 1.0
name = "MASTER PULSE TRIGGER SOURCE"

	[MASTERPULSE_TRIGGERSOURCE.support]
	1 = "EXTERNAL"
	2 = "SOFTWARE"

[MASTERPULSE_INTERVAL]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY", "AUTOROUNDING",]
TYPE = "REAL"
default = 0.09999999999999999
id = 1966144
max = 10.0
min = 9.999999999999999e-6
name = "MASTER PULSE INTERVAL"
step = 1e-6

[MASTERPULSE_BURSTTIMES]
ATTR = [ "WRITABLE", "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
default = 1.0
id = 1966160
max = 10000.0
min = 1.0
name = "MASTER PULSE BURST TIMES"
step = 1.0

[SYSTEM_ALIVE]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY", "VOLATILE",]
TYPE = "MODE"
default = 2.0
id = 16711696
max = 2.0
min = 1.0
name = "SYSTEM ALIVE"

	[SYSTEM_ALIVE.support]
	1 = "OFFLINE"
	2 = "ONLINE"

[CONVERSIONFACTOR_COEFF]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 16769040
name = "CONVERSION FACTOR COEFF"

[CONVERSIONFACTOR_OFFSET]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 16769056
name = "CONVERSION FACTOR OFFSET"

[NUMBEROF_VIEW]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
default = 1.0
id = 4325824
max = 2.0
min = 1.0
name = "NUMBER OF VIEW"
step = 1.0

[IMAGEDETECTOR_PIXELWIDTH]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4327440
max = 6.5
min = 6.5
name = "IMAGE DETECTOR PIXEL WIDTH"
step = 0.0

[IMAGEDETECTOR_PIXELHEIGHT]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "REAL"
id = 4327456
max = 6.5
min = 6.5
name = "IMAGE DETECTOR PIXEL HEIGHT"
step = 0.0

[IMAGEDETECTOR_PIXELNUMHORZ]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4327472
max = 2048.0
min = 2048.0
name = "IMAGE DETECTOR PIXEL NUM HORZ"
step = 0.0

[IMAGEDETECTOR_PIXELNUMVERT]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "LONG"
id = 4327488
max = 2048.0
min = 2048.0
name = "IMAGE DETECTOR PIXEL NUM VERT"
step = 0.0

[TIMESTAMP_PRODUCER]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 5.0
id = 4262416
max = 5.0
min = 5.0
name = "TIME STAMP PRODUCER"

	[TIMESTAMP_PRODUCER.support]
	1 = "IMAGING DEVICE"

[FRAMESTAMP_PRODUCER]
ATTR = [ "READABLE", "ACCESSREADY", "ACCESSBUSY",]
TYPE = "MODE"
default = 5.0
id = 4262432
max = 5.0
min = 5.0
name = "FRAME STAMP PRODUCER"

	[FRAMESTAMP_PRODUCER.support]
	1 = "IMAGING DEVICE"
